/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class ManagerMainPage extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMainPage
     */
    public ManagerMainPage() {
        initComponents();
        
        execute();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSidebar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnMenu = new javax.swing.JPanel();
        pnManagerTitle = new javax.swing.JPanel();
        lblManagerTitle = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnSidebar.setBackground(new java.awt.Color(153, 153, 153));
        pnSidebar.setPreferredSize(new java.awt.Dimension(200, 500));
        pnSidebar.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(153, 153, 153));
        pnMenu.setLayout(new javax.swing.BoxLayout(pnMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pnMenu);

        pnSidebar.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnManagerTitle.setBackground(new java.awt.Color(102, 102, 102));

        lblManagerTitle.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblManagerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagerTitle.setText("Manager Main Page");

        javax.swing.GroupLayout pnManagerTitleLayout = new javax.swing.GroupLayout(pnManagerTitle);
        pnManagerTitle.setLayout(pnManagerTitleLayout);
        pnManagerTitleLayout.setHorizontalGroup(
            pnManagerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManagerTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManagerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnManagerTitleLayout.setVerticalGroup(
            pnManagerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManagerTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManagerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnSidebar.add(pnManagerTitle, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnSidebar, java.awt.BorderLayout.LINE_START);

        pnContent.setBackground(new java.awt.Color(255, 255, 255));

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1014, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pnMain.add(new View_Booking_Record());
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManagerTitle;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnManagerTitle;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnSidebar;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        //Sales Dashboard menu
        MenuItem S_vbr = new MenuItem(null,false,null,"    View Booking Record", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pnMain.removeAll();
                pnMain.add(new View_Booking_Record());
                pnMain.repaint();
                pnMain.revalidate();
            }
        },2);
        MenuItem S_sm = new MenuItem(null,false,null,"    Sales Monitoring", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pnMain.removeAll();
                pnMain.add(new Sales_Monitoring());
                pnMain.repaint();
                pnMain.revalidate();
            }
        },2);
        MenuItem S_vtp = new MenuItem(null,false,null,"    View Top Performances", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pnMain.removeAll();
                pnMain.add(new View_Top_Performance());
                pnMain.repaint();
                pnMain.revalidate();
            }
        },2);
        
        
        
        //Maintenance Dashboard menu
        MenuItem M_vcf = new MenuItem(null,false,null,"  View Customer Feedback",new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pnMain.removeAll();
                pnMain.add(new View_Customer_Feedback());
                pnMain.repaint();
                pnMain.revalidate();
            }
        },2);
        MenuItem M_sa = new MenuItem(null,false,null,"  Scheduler Assignment", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pnMain.removeAll();
                pnMain.add(new Scheduler_Assignment());
                pnMain.repaint();
                pnMain.revalidate();
            }
        },2);
        
        //Manager menu
        MenuItem menuSalesDashboard = new MenuItem(null,false,null,"Sales Dashboard",null,1,S_vbr,S_sm,S_vtp);
        MenuItem menuMaintenanceDashboard = new MenuItem(null,false,null,"Maintenance Dashboard",null,1,M_vcf,M_sa);
        MenuItem menuProfile = new MenuItem(null,false,null,"Profile",null,1);
        MenuItem menuLogOut = new MenuItem(null,false,null,"Log Out",null,1);
        
        addMenu(menuSalesDashboard,menuMaintenanceDashboard,menuProfile,menuLogOut);
    }
    
    private void addMenu(MenuItem...menu){
        for (int i = 0; i< menu.length;i++){
            pnMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for(MenuItem m: subMenu){
                addMenu(m);
            }
        }
        pnMenu.revalidate();
    }
}
