/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Manager_Class_File.Manager_SalesMonitor;
import Manager_Class_File.Manager_SalesRecord;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Sales_Monitoring extends javax.swing.JPanel {

    /**
     * Creates new form Weekly_Sales
     */
    public Sales_Monitoring() {
        initComponents();
        populateYearComboBox(); // Populate the year combo box when the panel is created
        salesMonitor = new Manager_SalesMonitor(); // Initialize sales monitor class
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        pn_SM_content = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        lbl_SM_content1 = new javax.swing.JLabel();
        cbo_SM_year = new javax.swing.JComboBox<>();
        btn_SM_view = new javax.swing.JButton();
        lbl_SM_content3 = new javax.swing.JLabel();
        cbo_SM_salestype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SM_salesresult = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        main_Panel.setLayout(new java.awt.CardLayout());

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("Sales Monitoring");

        lbl_SM_content1.setText("Select a Year : ");

        btn_SM_view.setText("View");
        btn_SM_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SM_viewActionPerformed(evt);
            }
        });

        lbl_SM_content3.setText("View Sales By :");

        cbo_SM_salestype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Yearly" }));

        tbl_SM_salesresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tbl_SM_salesresult);

        javax.swing.GroupLayout pn_SM_contentLayout = new javax.swing.GroupLayout(pn_SM_content);
        pn_SM_content.setLayout(pn_SM_contentLayout);
        pn_SM_contentLayout.setHorizontalGroup(
            pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SM_contentLayout.createSequentialGroup()
                .addGroup(pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SM_contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_SM_contentLayout.createSequentialGroup()
                                .addComponent(lbl_SM_content3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_SM_salestype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pn_SM_contentLayout.createSequentialGroup()
                                    .addComponent(lbl_SM_content1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbo_SM_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_Title1)))
                        .addGap(0, 598, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_SM_contentLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_SM_view)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_SM_contentLayout.setVerticalGroup(
            pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SM_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SM_content1)
                    .addComponent(cbo_SM_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SM_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SM_content3)
                    .addComponent(cbo_SM_salestype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SM_view)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        main_Panel.add(pn_SM_content, "card2");

        add(main_Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SM_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SM_viewActionPerformed
        String selectedYear = (String) cbo_SM_year.getSelectedItem();
        String selectedSalesType = (String) cbo_SM_salestype.getSelectedItem();

        if (selectedYear == null || selectedSalesType == null) {
            JOptionPane.showMessageDialog(this, "Please select a year and a sales type.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Set table headers based on the sales type
        setTableColumnsBasedOnSalesType(selectedSalesType);
        
        // Fetch sales data and populate the table
        List<Manager_SalesRecord> records = Manager_SalesMonitor.getSalesRecords(selectedYear, selectedSalesType);
        DefaultTableModel model = (DefaultTableModel) tbl_SM_salesresult.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Manager_SalesRecord record : records) {
            model.addRow(record.getRowData());
        }
    }//GEN-LAST:event_btn_SM_viewActionPerformed
                                            
    // Method to populate the year combo box based on the Booking file
    private void populateYearComboBox() {
        Set<String> years = new HashSet<>(); // Using Set to avoid duplicate years

        try (BufferedReader br = new BufferedReader(new FileReader("Payment.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(","); 
                if (data.length > 0) { // Ensure StartTime exists
                    String paymentTime = data[3]; // Assuming StartTime is at index 2
                    String year = paymentTime.split("-")[0]; // Extract year
                    years.add(year);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Populate combo box with the years
        cbo_SM_year.removeAllItems();
        for (String year : years) {
            cbo_SM_year.addItem(year);
        }
    }
    
    // Method to dynamically set table columns based on the selected sales type
    private void setTableColumnsBasedOnSalesType(String salesType) {
        DefaultTableModel model = (DefaultTableModel) tbl_SM_salesresult.getModel();

        // Clear the existing columns
        model.setColumnCount(0);

        // Set new columns based on the sales type
        switch (salesType) {
            case "Weekly":
                model.setColumnIdentifiers(new String[] { "Week Number", "Total Sales", "Total Bookings" });
                break;
            case "Monthly":
                model.setColumnIdentifiers(new String[] { "Month", "Total Sales", "Total Bookings" });
                break;
            case "Yearly":
                model.setColumnIdentifiers(new String[] { "Year", "Total Sales", "Total Bookings" });
                break;
            default:
                throw new IllegalArgumentException("Invalid sales type selected.");
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SM_view;
    private javax.swing.JComboBox<String> cbo_SM_salestype;
    private javax.swing.JComboBox<String> cbo_SM_year;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_SM_content1;
    private javax.swing.JLabel lbl_SM_content3;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel pn_SM_content;
    private javax.swing.JTable tbl_SM_salesresult;
    // End of variables declaration//GEN-END:variables
}
