/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

/**
 *
 * @author User
 */
public class Scheduler_Assignment extends javax.swing.JPanel {

    /**
     * Creates new form Scheduler_Assignment
     */
    public Scheduler_Assignment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        pn_SA_home = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        lbl_SA_content1 = new javax.swing.JLabel();
        cbo_VCF_feedbacktype = new javax.swing.JComboBox<>();
        lbl_SA_content2 = new javax.swing.JLabel();
        cbo_VCF_feedbacktype1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SA_schedulerassignment = new javax.swing.JTable();
        lbl_SA_content3 = new javax.swing.JLabel();
        txt_SA_searchassignmentID = new javax.swing.JTextField();
        btn_SA_view = new javax.swing.JButton();
        btn_SA_assign = new javax.swing.JButton();
        btn_SA_update = new javax.swing.JButton();
        btn_SA_viewhallmaintenance = new javax.swing.JButton();
        pn_SA_assign = new javax.swing.JPanel();
        lbl_Title2 = new javax.swing.JLabel();
        lbl_SA_content4 = new javax.swing.JLabel();
        lbl_SA_content5 = new javax.swing.JLabel();
        btn_SA_cancel = new javax.swing.JButton();
        btn_SA_confirm = new javax.swing.JButton();
        txt_SA_assignmentID = new javax.swing.JTextField();
        txt_SA_issueID = new javax.swing.JTextField();
        lbl_SA_content7 = new javax.swing.JLabel();
        txt_SA_hallID = new javax.swing.JTextField();
        lbl_SA_content8 = new javax.swing.JLabel();
        txt_SA_managerID = new javax.swing.JTextField();
        lbl_SA_content9 = new javax.swing.JLabel();
        cbo_SA_assignScheduler = new javax.swing.JComboBox<>();
        lbl_SA_content10 = new javax.swing.JLabel();
        cbo_SA_IssueStatus = new javax.swing.JComboBox<>();
        lbl_SA_content11 = new javax.swing.JLabel();
        txt_SA_remark = new javax.swing.JTextField();
        pn_SA_update = new javax.swing.JPanel();
        lbl_Title3 = new javax.swing.JLabel();
        lbl_SA_content6 = new javax.swing.JLabel();
        lbl_SA_content12 = new javax.swing.JLabel();
        btn_USA_cancel = new javax.swing.JButton();
        btn_USA_update = new javax.swing.JButton();
        txt_USA_assignmentID = new javax.swing.JTextField();
        txt_USA_issueID = new javax.swing.JTextField();
        lbl_SA_content13 = new javax.swing.JLabel();
        txt_USA_hallID = new javax.swing.JTextField();
        lbl_SA_content14 = new javax.swing.JLabel();
        txt_USA_managerID = new javax.swing.JTextField();
        lbl_SA_content15 = new javax.swing.JLabel();
        cbo_USA_assignScheduler = new javax.swing.JComboBox<>();
        lbl_SA_content16 = new javax.swing.JLabel();
        cbo_USA_IssueStatus = new javax.swing.JComboBox<>();
        lbl_SA_content17 = new javax.swing.JLabel();
        txt_USA_remark = new javax.swing.JTextField();
        pn_SA_viewHallMaintenance = new javax.swing.JPanel();
        lbl_Title4 = new javax.swing.JLabel();
        lbl_SA_content18 = new javax.swing.JLabel();
        cbo_HM_maintenanceStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HM_hallMaintenance = new javax.swing.JTable();
        lbl_SA_content20 = new javax.swing.JLabel();
        txt_HM_searchassignmentID = new javax.swing.JTextField();
        btn_HM_view = new javax.swing.JButton();
        btn_HM_back = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        main_Panel.setLayout(new java.awt.CardLayout());

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("Scheduler Assignment");

        lbl_SA_content1.setText("View Assignments :");

        cbo_VCF_feedbacktype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SA_content2.setText("Select Issue Status :");

        cbo_VCF_feedbacktype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_SA_schedulerassignment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_SA_schedulerassignment);

        lbl_SA_content3.setText("Quick Search : Enter Assignment ID to Search (format)");

        txt_SA_searchassignmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SA_searchassignmentIDActionPerformed(evt);
            }
        });

        btn_SA_view.setText("View");

        btn_SA_assign.setText("Assign");
        btn_SA_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_assignActionPerformed(evt);
            }
        });

        btn_SA_update.setText("Update");
        btn_SA_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_updateActionPerformed(evt);
            }
        });

        btn_SA_viewhallmaintenance.setText("View Hall Maintenance");
        btn_SA_viewhallmaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_viewhallmaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_SA_homeLayout = new javax.swing.GroupLayout(pn_SA_home);
        pn_SA_home.setLayout(pn_SA_homeLayout);
        pn_SA_homeLayout.setHorizontalGroup(
            pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_homeLayout.createSequentialGroup()
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Title1)
                            .addGroup(pn_SA_homeLayout.createSequentialGroup()
                                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                                        .addComponent(lbl_SA_content1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbo_VCF_feedbacktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                                        .addComponent(lbl_SA_content2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbo_VCF_feedbacktype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(130, 130, 130)
                                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_SA_content3)
                                    .addComponent(txt_SA_searchassignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_SA_view))
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_SA_viewhallmaintenance)
                        .addGap(76, 76, 76)
                        .addComponent(btn_SA_assign)
                        .addGap(89, 89, 89)
                        .addComponent(btn_SA_update)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pn_SA_homeLayout.setVerticalGroup(
            pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SA_content1)
                            .addComponent(cbo_VCF_feedbacktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SA_content2)
                            .addComponent(cbo_VCF_feedbacktype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content3)
                        .addGap(2, 2, 2)
                        .addComponent(txt_SA_searchassignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SA_view)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SA_assign)
                    .addComponent(btn_SA_update)
                    .addComponent(btn_SA_viewhallmaintenance))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        main_Panel.add(pn_SA_home, "card2");

        lbl_Title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title2.setText("Scheduler Assignment");

        lbl_SA_content4.setText("Assignment ID :");

        lbl_SA_content5.setText("Issue ID :");

        btn_SA_cancel.setText("Cancel");
        btn_SA_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_cancelActionPerformed(evt);
            }
        });

        btn_SA_confirm.setText("Confirm");

        lbl_SA_content7.setText("Hall ID :");

        lbl_SA_content8.setText("Manager ID : (Auto-filled)");

        lbl_SA_content9.setText("Assign Scheduler :");

        cbo_SA_assignScheduler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SA_content10.setText("Issue Status :");

        cbo_SA_IssueStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SA_content11.setText("Remark (Optional) :");

        javax.swing.GroupLayout pn_SA_assignLayout = new javax.swing.GroupLayout(pn_SA_assign);
        pn_SA_assign.setLayout(pn_SA_assignLayout);
        pn_SA_assignLayout.setHorizontalGroup(
            pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_assignLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SA_assignLayout.createSequentialGroup()
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content4)
                            .addComponent(txt_SA_assignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content7)
                            .addComponent(txt_SA_hallID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content5)
                            .addComponent(txt_SA_issueID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content8)
                            .addComponent(txt_SA_managerID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_SA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content9)
                            .addComponent(cbo_SA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content10)
                            .addComponent(lbl_SA_content11)
                            .addComponent(txt_SA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_SA_confirm)
                            .addComponent(lbl_Title2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SA_cancel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_SA_assignLayout.setVerticalGroup(
            pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_assignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_SA_assignLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SA_issueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SA_managerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SA_assignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SA_hallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_SA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_SA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SA_cancel)
                            .addComponent(btn_SA_confirm))
                        .addGap(21, 21, 21)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        main_Panel.add(pn_SA_assign, "card2");

        lbl_Title3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title3.setText("Update Scheduler Assignment");

        lbl_SA_content6.setText("Assignment ID :");

        lbl_SA_content12.setText("Issue ID :");

        btn_USA_cancel.setText("Cancel");
        btn_USA_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_USA_cancelActionPerformed(evt);
            }
        });

        btn_USA_update.setText("Update");

        lbl_SA_content13.setText("Hall ID :");

        lbl_SA_content14.setText("Manager ID : (Auto-filled)");

        lbl_SA_content15.setText("Assign Scheduler :");

        cbo_USA_assignScheduler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SA_content16.setText("Issue Status :");

        cbo_USA_IssueStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SA_content17.setText("Remark (Optional) :");

        javax.swing.GroupLayout pn_SA_updateLayout = new javax.swing.GroupLayout(pn_SA_update);
        pn_SA_update.setLayout(pn_SA_updateLayout);
        pn_SA_updateLayout.setHorizontalGroup(
            pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SA_updateLayout.createSequentialGroup()
                        .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content6)
                            .addComponent(txt_USA_assignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content13)
                            .addComponent(txt_USA_hallID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content12)
                            .addComponent(txt_USA_issueID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content14)
                            .addComponent(txt_USA_managerID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))
                    .addGroup(pn_SA_updateLayout.createSequentialGroup()
                        .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_USA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content15)
                            .addComponent(cbo_USA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content16)
                            .addComponent(lbl_SA_content17)
                            .addComponent(txt_USA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_SA_updateLayout.createSequentialGroup()
                        .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_USA_update)
                            .addComponent(lbl_Title3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_USA_cancel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_SA_updateLayout.setVerticalGroup(
            pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_SA_updateLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_USA_issueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_USA_managerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_SA_updateLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_USA_assignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_USA_hallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_USA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_USA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SA_content17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_USA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_SA_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_USA_cancel)
                            .addComponent(btn_USA_update))
                        .addGap(21, 21, 21)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        main_Panel.add(pn_SA_update, "card2");

        lbl_Title4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title4.setText("Hall Maintenance");

        lbl_SA_content18.setText("View Maintenance Status :");

        cbo_HM_maintenanceStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_HM_hallMaintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_HM_hallMaintenance);

        lbl_SA_content20.setText("Quick Search : Enter Assignment ID to Search (format)");

        txt_HM_searchassignmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HM_searchassignmentIDActionPerformed(evt);
            }
        });

        btn_HM_view.setText("View");

        btn_HM_back.setText("Back");
        btn_HM_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HM_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_SA_viewHallMaintenanceLayout = new javax.swing.GroupLayout(pn_SA_viewHallMaintenance);
        pn_SA_viewHallMaintenance.setLayout(pn_SA_viewHallMaintenanceLayout);
        pn_SA_viewHallMaintenanceLayout.setHorizontalGroup(
            pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_HM_maintenanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content20)
                            .addComponent(txt_HM_searchassignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Title4)
                            .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn_HM_view)
                                .addGap(56, 56, 56)
                                .addComponent(btn_HM_back))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_SA_viewHallMaintenanceLayout.setVerticalGroup(
            pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_SA_content18)
                        .addComponent(cbo_HM_maintenanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content20)
                        .addGap(2, 2, 2)
                        .addComponent(txt_HM_searchassignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_HM_view)
                    .addComponent(btn_HM_back))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_Panel.add(pn_SA_viewHallMaintenance, "card2");

        add(main_Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SA_searchassignmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SA_searchassignmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SA_searchassignmentIDActionPerformed

    private void txt_HM_searchassignmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HM_searchassignmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HM_searchassignmentIDActionPerformed

    private void btn_SA_viewhallmaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_viewhallmaintenanceActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
        
        main_Panel.add(pn_SA_viewHallMaintenance);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_SA_viewhallmaintenanceActionPerformed

    private void btn_SA_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_assignActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
        
        main_Panel.add(pn_SA_assign);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_SA_assignActionPerformed

    private void btn_SA_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_updateActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
        
        main_Panel.add(pn_SA_update);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_SA_updateActionPerformed

    private void btn_SA_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_cancelActionPerformed
        main_Panel.removeAll();
        main_Panel.add(pn_SA_home);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_SA_cancelActionPerformed

    private void btn_USA_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_USA_cancelActionPerformed
        main_Panel.removeAll();
        main_Panel.add(pn_SA_home);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_USA_cancelActionPerformed

    private void btn_HM_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HM_backActionPerformed
        main_Panel.removeAll();
        main_Panel.add(pn_SA_home);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_HM_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HM_back;
    private javax.swing.JButton btn_HM_view;
    private javax.swing.JButton btn_SA_assign;
    private javax.swing.JButton btn_SA_cancel;
    private javax.swing.JButton btn_SA_confirm;
    private javax.swing.JButton btn_SA_update;
    private javax.swing.JButton btn_SA_view;
    private javax.swing.JButton btn_SA_viewhallmaintenance;
    private javax.swing.JButton btn_USA_cancel;
    private javax.swing.JButton btn_USA_update;
    private javax.swing.JComboBox<String> cbo_HM_maintenanceStatus;
    private javax.swing.JComboBox<String> cbo_SA_IssueStatus;
    private javax.swing.JComboBox<String> cbo_SA_assignScheduler;
    private javax.swing.JComboBox<String> cbo_USA_IssueStatus;
    private javax.swing.JComboBox<String> cbo_USA_assignScheduler;
    private javax.swing.JComboBox<String> cbo_VCF_feedbacktype;
    private javax.swing.JComboBox<String> cbo_VCF_feedbacktype1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_SA_content1;
    private javax.swing.JLabel lbl_SA_content10;
    private javax.swing.JLabel lbl_SA_content11;
    private javax.swing.JLabel lbl_SA_content12;
    private javax.swing.JLabel lbl_SA_content13;
    private javax.swing.JLabel lbl_SA_content14;
    private javax.swing.JLabel lbl_SA_content15;
    private javax.swing.JLabel lbl_SA_content16;
    private javax.swing.JLabel lbl_SA_content17;
    private javax.swing.JLabel lbl_SA_content18;
    private javax.swing.JLabel lbl_SA_content2;
    private javax.swing.JLabel lbl_SA_content20;
    private javax.swing.JLabel lbl_SA_content3;
    private javax.swing.JLabel lbl_SA_content4;
    private javax.swing.JLabel lbl_SA_content5;
    private javax.swing.JLabel lbl_SA_content6;
    private javax.swing.JLabel lbl_SA_content7;
    private javax.swing.JLabel lbl_SA_content8;
    private javax.swing.JLabel lbl_SA_content9;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JLabel lbl_Title2;
    private javax.swing.JLabel lbl_Title3;
    private javax.swing.JLabel lbl_Title4;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel pn_SA_assign;
    private javax.swing.JPanel pn_SA_home;
    private javax.swing.JPanel pn_SA_update;
    private javax.swing.JPanel pn_SA_viewHallMaintenance;
    private javax.swing.JTable tbl_HM_hallMaintenance;
    private javax.swing.JTable tbl_SA_schedulerassignment;
    private javax.swing.JTextField txt_HM_searchassignmentID;
    private javax.swing.JTextField txt_SA_assignmentID;
    private javax.swing.JTextField txt_SA_hallID;
    private javax.swing.JTextField txt_SA_issueID;
    private javax.swing.JTextField txt_SA_managerID;
    private javax.swing.JTextField txt_SA_remark;
    private javax.swing.JTextField txt_SA_searchassignmentID;
    private javax.swing.JTextField txt_USA_assignmentID;
    private javax.swing.JTextField txt_USA_hallID;
    private javax.swing.JTextField txt_USA_issueID;
    private javax.swing.JTextField txt_USA_managerID;
    private javax.swing.JTextField txt_USA_remark;
    // End of variables declaration//GEN-END:variables
}
