/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Manager_Class_File.Manager_BookingRecord;
import Manager_Class_File.Manager_File_Operation;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class View_Booking_Record extends javax.swing.JPanel {

    /**
     * Creates new form content
     */
    public View_Booking_Record() {
        initComponents();
        populateYearComboBox(); // Populate the year combo box when the panel is created
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_VBR_content = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        lbl_VBR_content1 = new javax.swing.JLabel();
        cbo_VBR_year = new javax.swing.JComboBox<>();
        lbl_VBR_content3 = new javax.swing.JLabel();
        txt_VBR_searchdate = new javax.swing.JTextField();
        btn_VBR_view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_VBR_bookingrecord = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("View Booking Record");

        lbl_VBR_content1.setText("Select a Year : ");

        lbl_VBR_content3.setText("Quick Search : Enter Date to Search (YYYY-MM-DD)");

        txt_VBR_searchdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VBR_searchdateActionPerformed(evt);
            }
        });

        btn_VBR_view.setText("View");
        btn_VBR_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VBR_viewActionPerformed(evt);
            }
        });

        tbl_VBR_bookingrecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Start Time", "End Time", "Booking ID", "Customer ID", "Hall ID", "Reservation Number of People", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(tbl_VBR_bookingrecord);

        javax.swing.GroupLayout pn_VBR_contentLayout = new javax.swing.GroupLayout(pn_VBR_content);
        pn_VBR_content.setLayout(pn_VBR_contentLayout);
        pn_VBR_contentLayout.setHorizontalGroup(
            pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VBR_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_VBR_contentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_VBR_contentLayout.createSequentialGroup()
                        .addGroup(pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_VBR_contentLayout.createSequentialGroup()
                                .addComponent(lbl_VBR_content1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_VBR_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Title1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_VBR_content3)
                            .addComponent(txt_VBR_searchdate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209))))
            .addGroup(pn_VBR_contentLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btn_VBR_view)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_VBR_contentLayout.setVerticalGroup(
            pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VBR_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_VBR_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_VBR_content1)
                    .addComponent(cbo_VBR_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_VBR_content3))
                .addGap(2, 2, 2)
                .addComponent(txt_VBR_searchdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btn_VBR_view)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        mainPanel.add(pn_VBR_content, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VBR_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VBR_viewActionPerformed
        String selectedYear = cbo_VBR_year.getSelectedItem().toString();
        String searchDate = txt_VBR_searchdate.getText().trim();

        // Check if selectedYear or selectedHall is null
        if (selectedYear == null) {
            JOptionPane.showMessageDialog(this, "Please select a year and a hall type.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if input is invalid
        }
        
        Manager_File_Operation fileOperation = new Manager_File_Operation();
        List<Manager_BookingRecord> records = fileOperation.fetchBookingRecords(selectedYear, searchDate);

        DefaultTableModel model = (DefaultTableModel) tbl_VBR_bookingrecord.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Manager_BookingRecord record : records) {
            String bookingDate = record.getStartTime().split(" ")[0]; // Extract booking date
            String startTime = record.getStartTime().split(" ")[1]; // Extract start time
            String endTime = record.getEndTime().split(" ")[1]; // Extract end time

            model.addRow(new Object[]{
                bookingDate,
                startTime,
                endTime,
                record.getBookingId(),
                record.getCustomerId(),
                record.getHallId(),
                record.getReservationPeople(),
                record.getTotalAmount()
            });
        }
    }//GEN-LAST:event_btn_VBR_viewActionPerformed

    private void txt_VBR_searchdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VBR_searchdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_VBR_searchdateActionPerformed

    // Method to populate the year combo box based on the Booking file
    private void populateYearComboBox() {
        Set<String> years = new HashSet<>(); // Using Set to avoid duplicate years

        try (BufferedReader br = new BufferedReader(new FileReader("Booking.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(","); 
                if (data.length > 2) { // Ensure StartTime exists
                    String startTime = data[2]; // Assuming StartTime is at index 2
                    String year = startTime.split("-")[0]; // Extract year
                    years.add(year);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Populate combo box with the years
        cbo_VBR_year.removeAllItems();
        for (String year : years) {
            cbo_VBR_year.addItem(year);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_VBR_view;
    private javax.swing.JComboBox<String> cbo_VBR_year;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JLabel lbl_VBR_content1;
    private javax.swing.JLabel lbl_VBR_content3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_VBR_content;
    private javax.swing.JTable tbl_VBR_bookingrecord;
    private javax.swing.JTextField txt_VBR_searchdate;
    // End of variables declaration//GEN-END:variables
}
