/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

/**
 *
 * @author User
 */
public class View_Customer_Feedback extends javax.swing.JPanel {

    /**
     * Creates new form View_Customer_Feedback
     */
    public View_Customer_Feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        pn_VCF_content = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        lbl_VCF_content1 = new javax.swing.JLabel();
        cbo_VCF_feedbacktype = new javax.swing.JComboBox<>();
        btn_VCF_view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_VCF_feedback = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        main_Panel.setLayout(new java.awt.CardLayout());

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("View Customer Feedback");

        lbl_VCF_content1.setText("Select a Type :");

        cbo_VCF_feedbacktype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_VCF_view.setText("View");
        btn_VCF_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VCF_viewActionPerformed(evt);
            }
        });

        tbl_VCF_feedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_VCF_feedback);

        javax.swing.GroupLayout pn_VCF_contentLayout = new javax.swing.GroupLayout(pn_VCF_content);
        pn_VCF_content.setLayout(pn_VCF_contentLayout);
        pn_VCF_contentLayout.setHorizontalGroup(
            pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                    .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                        .addGroup(pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                                .addComponent(lbl_VCF_content1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_VCF_feedbacktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Title1)
                            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btn_VCF_view)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_VCF_contentLayout.setVerticalGroup(
            pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_VCF_content1)
                    .addComponent(cbo_VCF_feedbacktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_VCF_view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        main_Panel.add(pn_VCF_content, "card2");

        add(main_Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VCF_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VCF_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VCF_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_VCF_view;
    private javax.swing.JComboBox<String> cbo_VCF_feedbacktype;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JLabel lbl_VCF_content1;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel pn_VCF_content;
    private javax.swing.JTable tbl_VCF_feedback;
    // End of variables declaration//GEN-END:variables
}
